Algoritmo "ANO QUE TERÁ EM 2050"

Var
   ano_atual,ano_nascimento : INTEIRO
   IDADE, IDADE_2050 : INTEIRO
Inicio
      ESCREVA ("ANO ATUAL: ")
      LEIA (ano_atual)
      ESCREVA ("ANO DE NASCIMENTO: ")
      LEIA (ano_nascimento)
      
      IDADE <- ( ano_atual - ano_nascimento )
      IDADE_2050 <- ( 2050 - ano_nascimento )

      ESCREVAL ("IDADE ATUAL: ", IDADE)
      ESCREVAL ("IDADE NOS ANOS DE 2050: ", IDADE_2050)



Fimalgoritmo