a = input('Digite algo:')
print('O tipo primitivo é', type(a))
print('Só tem espaços?',a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?',a.isalpha())
print('Ele é alfanúmerico?',a.isalnum())
print('Está em maiusculas?',a.isupper())
print('Está em minusculas?',a.islower())
print('Está capitalizada?',a.istitle())
