nome = str ( input ('ESCREVA NOME : ')).strip()
print ('MAIUSCULO >>> {}'.format (nome.upper()))
print ('EM MINUSCULO >>> {} '.format ( nome.lower()))
#print ('INICIAL MAIUSCULA  >>> {} '.format (nome.capitalize())) 
#print ('INICIAL DAS PALAVRAS MAIUSCULAS >>> {} '.format(nome.title()) )
print ( 'NOME TEM {} LETRAS '.format(len(nome) - nome.count(' ')))
#print ('PRIMEIRO NOME TEM {} LETRAS '.format (nome.find(' ')))
nome = nome.split(' ')
print ('PRIMEIRO NOME "{}", TEM {} LETRAS '.format (nome[0], len (nome[0])))
